# Site
repository: 0xDanielLopez/CV
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: (In progress)
title: Security Engineer
#email: brett.h@email.co.uk
website: daniel.tools

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 0xDanielLopez
github_username:  0xDanielLopez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 0xDanielLopez
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Daniel López, and I am a <mark>Security Engineer</mark> with over <mark>6 years of experience</mark> working in <mark>Security Operations Centers</mark> (SOC). Throughout these years, I have been involved in the analysis, containment and remediation of threats for international and strategic clients across multiple sectors.

  Also, in my spare time, I enjoy programming, building projects, and researching threats (which I often share on my Twitter account). I have a particular fondness for programming in <mark>Python & Bash</mark> and exploring technologies such as <mark>AWS</mark> or playing with <mark>APIs</mark>. These diverse interests enable me to stay up-to-date with the latest advancements in the field and continuously expand my skill set.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: phishunt
        link: phishunt.io
        # link_text: Project Website
        #additional_links:
        #  - title:  phishunt.io
        #    icon: fa-solid fa-fish
        #    url: phishunt.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Free feed of active phishing cases
        description: | # this will include new lines to allow paragraphs
          Website designed to identify and monitor possible active phishing cases. Searches suspicious websites, take a screenshot, grab some details (like IP, hosting provider OR certificate) and serve them in a Free Feed. This is a website built with <mark>Django</mark> / <mark>Bootstrap</mark> in frontend and <mark>Python</mark> / <mark>Bash</mark> in backend.
      - layout: top-middle
        title: TweetFeed
        link: tweetfeed.live
        # link_text: Project Website
        #additional_links:
        #  - title:  tweetfeed.live
        #    icon: fa-solid fa-shield
        #    url: tweetfeed.live
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Free freed of Indicators Of Compromise (IOCs) shared at Twitter
        description: | # this will include new lines to allow paragraphs
          TweetFeed collects Indicators of Compromise (IOCs) shared by the infosec community at Twitter. Focused on URLs, domains, IPs and SHA256/MD5 hashes, TweetFeed serves a Free Feed with these data that are constantly shared by researchers at Twitter. TweetFeed is a website built mainly with <mark>Bootstrap</mark> / <mark>JavaScript</mark> in frontend and <mark>Python</mark> / <mark>Bash</mark> in backend.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Cloud Software Group
        link: cloud.com
        # link_text: boringcompany.com
        sub_title: Security Engineer
        caption: Oct. 2020 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            As a Security Engineer at the SOC of Cloud Software Group -multinational cloud computing and virtualization technology company (former Citrix)- I am responsible for analyzing, containing, and remediating all types of cyber threats (malware infections, mail campaigns, Fraud/Abuse cases, Data Loss Prevention...). In this role, I work primarily with <mark>Splunk</mark> as Security Information and Event Management (SIEM) tool, <mark>Microsoft Defender for Endpoint</mark> (MDE) as Endpoint Detection and Response (EDR) tool, and <mark>XSOAR</mark> as Security Orchestration, Automation and Response (SOAR) tool. I am also a member of the <mark>Cyber Threat Intelligence</mark> (CTI) team, where I research new kinds of threats and Tactics, Techniques and Procedures (TTPs), and stay up-to-date with emerging cyber threats.
      - layout: left
        title: Banco Santander
        link: bancosantander.es
        # link_text: boringcompany.com
        sub_title: Global SOC Security Analyst
        caption: Aug. 2018 - Oct. 2020
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            As a Cybersecurity Analyst at the SOC of Banco Santander-Spain's largest bank- I was responsible for managing all types of cybersecurity alerts and performing in-depth studies under direct request of customers. In this role I worked primarily with <mark>Splunk</mark> as SIEM, <mark>Falcon CrowdStrike</mark> as EDR solution and IBM Resilient as SOAR.
      - layout: left
        title: Deloitte
        link: deloitte.com
        # link_text: boringcompany.com
        sub_title: CyberSOC Security Analyst
        caption: Aug. 2017 - Aug. 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            As a Security Analyst at Deloitte's CyberSOC -largest professional services network- I analyzed and monitored all types of security alerts in real-time for multiple customers: <mark>Data Loss Prevention</mark> (DLP), Managed Security Service Provider (MSSP), and various Security Information and Event Management (SIEM) tools such as <mark>Splunk</mark> and <mark>QRADAR</mark>.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Sevilla
        caption: 2015 - 2019
        sub_title: Master's Degree in Telecommunications Engineering
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my Master's Degree in Telecommunications Engineering at the Universidad de Sevilla, I gained a deep understanding of the principles and practices of <mark>modern telecommunications networks and systems</mark>. Throughout my studies, I was exposed to a wide range of topics including <mark>network architectures</mark>, <mark>signal processing</mark>, <mark>wireless communications</mark>, and <mark>network security</mark>.
      - layout: left
        title: Universidad de Sevilla
        caption: 2011 - 2015
        sub_title: Bachelor's Degree in Telecommunications Engineering Technology
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I completed my Bachelor's Degree in Telecommunications Engineering Technology at the Universidad de Sevilla, where I gained a comprehensive understanding of the fundamental principles and practices of <mark>telecommunications engineering</mark> as well as developed my <mark>computer science</mark> and <mark>programming skills</mark>.

  - title: Certifications and Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - GIAC Security Essentials (GSEC) / SANS SEC401 [[link](https://www.credly.com/badges/3045d920-1095-46ce-9c95-e136e706bcf1)]
      - Security Engineering on AWS [[link](https://www.aws.training/Transcript/CompletionCertificateHtml?transcriptid=OB3d3Fgom0a6uA1HoOTUXg2)]
      - Architecting on AWS – Accelerator [[link](https://www.aws.training/Transcript/CompletionCertificateHtml?transcriptid=XZWgjfzfeE6XFZx6_lR8kg2)]
      - ITIL Foundation [[link](https://bit.ly/2AHfQsI)]
      - Scrum Foundation Professional Certificate [[link](https://www.youracclaim.com/badges/64714c5d-07c1-4f27-84a5-e8cfcf3247c7)]

  - title: At News / Media
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Telenotícies migdia - 12/04/2023 [[Spanish midday newscast ~32.15](https://www.ccma.cat/tv3/alacarta/telenoticies/telenoticies-migdia-12042023/video/6214413/)]
      - Siguen las campañas de phishing suplantando a la Agencia Tributaria, ahora también por sms [[ESET blog](https://blogs.protegerse.com/2023/04/11/siguen-las-campanas-de-phishing-suplantando-a-la-agencia-tributaria-ahora-tambien-por-sms/)]
      - Telegram abre paso a la venta de kits para suplantar webs como la de Correos a través de bots [[mundodeportivo.com](https://www.mundodeportivo.com/urbantecno/seguridad/telegram-abre-paso-a-la-venta-de-kits-para-suplantar-webs-como-la-de-correos-a-traves-de-bots)]
      - Están suplantando la web de Correos con kits vendidos en Telegram que usan sus bots para recopilar contraseñas. Y hay muchos kits así [[ciberpro.es](https://ciberpro.es/estan-suplantando-la-web-de-correos-con-kits-vendidos-en-telegram-que-usan-sus-bots-para-recopilar-contrasenas-y-hay-muchos-kits-asi/)]
      - Están suplantando la web de Correos con kits vendidos en Telegram que usan sus bots para recopilar contraseñas. Y hay muchos kits así [[genbeta.com](https://www.genbeta.com/seguridad/estan-suplantando-web-correos-kits-vendidos-telegram-que-usan-sus-bots-para-recopilar-contrasenas-hay-muchos-kits-asi)]

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Memmber of [CuratedIntel](https://twitter.com/CuratedIntel) trust group 
      - I'm [Enneagram Type 5](https://www.enneagraminstitute.com/type-5)
      - Enjoy riding my bike and going to the gym (helps me a lot avoiding burnout).
      - In free cycles also love playing videogames (mostly League of Legends or CounterStrike)

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
