# Site
repository: 0xDanielLopez/CV
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel López
title: Security Engineer
email: daniel.lopez.cv@gmail.com
website: daniel.tools

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 0xDanielLopez
github_username:  0xDanielLopez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 0xDanielLopez
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Daniel López, and I am a <mark>Cyber Threat Researcher</mark> with over <mark>7 years of experience</mark> working in <mark>Cybersecurity</mark>. Throughout these years, I have been involved in the analysis, containment and remediation of threats for multiple international clients across diverse sectors as well as the research of TTPs in the field.

  I enjoy <mark>coding</mark>, <mark>building projects</mark>, and <mark>researching threats</mark> and I have a particular fondness for coding in <mark>Python & Bash</mark> and exploring technologies such as <mark>AWS</mark> or playing with <mark>APIs</mark>.

  These diverse interests enable me to stay up-to-date with the latest advancements in the field and to be continually learning.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: TweetFeed
        link: tweetfeed.live
        # link_text: Project Website
        #additional_links:
        #  - title:  tweetfeed.live
        #    icon: fa-solid fa-shield
        #    url: tweetfeed.live
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Free feed of Indicators Of Compromise (IOCs) shared at Twitter
        description: | # this will include new lines to allow paragraphs
          TweetFeed collects <mark>Indicators of Compromise (IOCs) shared by the infosec community</mark> at Twitter. Focused on URLs, domains, IPs and SHA256/MD5 hashes, TweetFeed serves a Free Feed with these data that are constantly shared by researchers at Twitter.

          This is a website built mainly with <mark>Bootstrap</mark> / <mark>JavaScript</mark> in frontend and <mark>Python</mark> / <mark>Bash</mark> in backend.

      - layout: top-middle
        title: phishunt
        link: phishunt.io
        # link_text: Project Website
        #additional_links:
        #  - title:  phishunt.io
        #    icon: fa-solid fa-fish
        #    url: phishunt.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Free feed of active phishing cases
        description: | # this will include new lines to allow paragraphs
          Website designed to identify and monitor possible <mark>active phishing cases</mark>. Searches suspicious websites, take a screenshot, grab some details (like IP, hosting provider or certificate) and serves them in a Free Feed.

          This is a website built with <mark>Django</mark> / <mark>Bootstrap</mark> in frontend and <mark>Python</mark> / <mark>Bash</mark> in backend.
      
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:

      - layout: left
        title: Okta
        link: okta.com
        # link_text: boringcompany.com
        sub_title: Cyber Threat Researcher
        caption: Jun. 2024 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            I'm part of the Identity Threat Research Team at Okta. To be updated.

      - layout: left
        title: Cloud Software Group
        link: cloud.com
        # link_text: boringcompany.com
        sub_title: Sr. Security Engineer
        caption: Oct. 2020 - Jun. 2024
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Worked at the Security Operations Center of Cloud Software Group. Our mission was to protect the company from all type of cyberthreats and improve our security posture providing a 24/7 service.

            Key Responsibilities:

            - <mark>Analyzing, containing and remediating</mark> all types of cyberthreats (malware infections, mail campaigns, Fraud/Abuse cases, Insider Threat/Data Loss Prevention…)
            - <mark>Threat hunting</mark> and <mark>researching new malware/phishing campaigns</mark> providing specific mitigation and recommendation steps based on the investigation
            - <mark>Support SIEM and Detection Engineers</mark> to fine tune alerts reducing volumetry, improving performance and detection rate

            Technologies used in this role:

            <mark>AWS / Azure (Cloud)</mark> • <mark>Microsoft Defender for Endpoint / Falcon CrowdStrike (EDR)</mark> • <mark>Splunk (SIEM)</mark> • <mark>Cortex XSOAR (SOAR)</mark> 

      - layout: left
        title: Banco Santander
        link: bancosantander.es
        # link_text: boringcompany.com
        sub_title: Global SOC Security Analyst
        caption: Aug. 2018 - Oct. 2020
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Internal employee working at Banco Santander's Global SOC team providing 24/7 service and on-call rotation to all bank's entities worldwide.

            Key Responsibilities:

            - Perform <mark>monitoring, in-depth investigation and mitigation</mark> of security incidents
            - Monitor website's traffic and <mark>critical bank SWIFT assets</mark>. Follow-up standard operation procedures, playbooks and on-demand analysis of security alerts such as malware, phishing, DDoS or brute force attacks
            - <mark>Fraud prevention</mark>: manage phishings targeting employees, suspicious emails received by VIP directors, compromised credit cards, mule accounts, stolen corporate devices, data leaks, fake profiles in social media, repositories or apps in unofficial markets

            Technologies used in this role:

            <mark>AWS (Cloud)</mark> • <mark>Falcon CrowdStrike (EDR)</mark> • <mark>Splunk (SIEM)</mark> • <mark>IBM QRadar (SOAR)</mark> • <mark>Cisco Ironport (Proxy)</mark> • <mark>McAfee (IPS)</mark>
      - layout: left
        title: Deloitte
        link: deloitte.com
        # link_text: boringcompany.com
        sub_title: CyberSOC Security Analyst
        caption: Aug. 2017 - Aug. 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
           Security Analyst at Deloitte's CyberSOC serving as Managed Security Service Provider (MSSP) for several national and international customers.

            Key Responsibilities:

            - Conduct <mark>initial analysis</mark> of alerts from SIEM tools to identify potential security threats
            - <mark>Follow playbooks and procedures</mark> applying immediate containment and remediation measures to threats as needed
            - <mark>Escalate potential incidents</mark> to other teams with context and detailed data for further investigation

            Technologies used in this role:

            <mark>Splunk (SIEM)</mark> • <mark>QRadar (SIEM)</mark> • <mark>ArcSight (SIEM)</mark> • <mark>FireEye (IPS)</mark> • <mark>McAfee (ePO)</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Universidad de Sevilla
        caption: 2015 - 2019
        sub_title: Master's Degree in Telecommunications Engineering
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my Master's Degree in Telecommunications Engineering at University of Seville, I gained a deep understanding of the principles and practices of <mark>modern telecommunications networks and systems</mark>. Throughout my studies, I was exposed to a wide range of topics including <mark>network architectures</mark>, <mark>signal processing</mark>, <mark>wireless communications</mark> and <mark>network security</mark>.
      - layout: left
        title: Universidad de Sevilla
        caption: 2011 - 2015
        sub_title: Bachelor's Degree in Telecommunications Engineering
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I completed my Bachelor's Degree in Telecommunications Engineering at University of Seville, where I gained a comprehensive understanding of the fundamental principles and practices of <mark>telecommunications engineering</mark> as well as developed my <mark>computer science</mark> and <mark>programming skills</mark>.

  - title: Certifications and Courses
    layout: text
    content: | # this will include new lines to allow paragraphs
      - GIAC Security Essentials (GSEC) / SANS SEC401 [[badge](https://www.credly.com/badges/3045d920-1095-46ce-9c95-e136e706bcf1)]
      - MITRE ATT&CK Defender™ - Fundamentals Badge Training [[badge](https://app.cybrary.it/courses/api/certificate/CC-56c26349-5548-4619-a38c-0df53b14d9e2/view)]
      - MITRE ATT&CK Defender™ - Cyber Threat Intelligence Certification Training [[badge](https://app.cybrary.it/courses/api/certificate/CC-254c8437-e3d2-4b26-9751-616c4cb373d2/view)]
      - MITRE ATT&CK Defender™ - SOC Assessments Certification Training [[badge](https://app.cybrary.it/courses/api/certificate/CC-191e6bfa-82eb-4518-9ea2-dead674d886a/view)]
      - Security Engineering on AWS [[badge](https://www.aws.training/Transcript/CompletionCertificateHtml?transcriptid=OB3d3Fgom0a6uA1HoOTUXg2)]
      - Architecting on AWS – Accelerator [[badge](https://www.aws.training/Transcript/CompletionCertificateHtml?transcriptid=XZWgjfzfeE6XFZx6_lR8kg2)]
      - ITIL Foundation [[badge](https://bit.ly/2AHfQsI)]
      - Scrum Foundation Professional Certificate [[badge](https://www.youracclaim.com/badges/64714c5d-07c1-4f27-84a5-e8cfcf3247c7)]

  - title: At News / Media
    layout: text
    content: | # - xxx [[xxx](xxx)]
      - Telenotícies migdia - 12/04/2023 [[TV3 - midday TV news (~32.15)](https://www.ccma.cat/tv3/alacarta/telenoticies/telenoticies-migdia-12042023/video/6214413/)]
      - Telenotícies migdia - 02/06/2023 [[TV3 - midday TV news (~27:48)](https://www.ccma.cat/tv3/alacarta/telenoticies/telenoticies-migdia-02062023/video/6224081/)]
      - Se ofrece ciberataque gratis en Telegram: el nuevo anzuelo de los robos 'online' [[elconfidencial.com](https://www.elconfidencial.com/tecnologia/2023-04-26/ciberataque-phishing-gratis-telegram-robos-online_3613307/)]
      - Siguen las campañas de phishing suplantando a la Agencia Tributaria, ahora también por SMS [[ESET blog](https://blogs.protegerse.com/2023/04/11/siguen-las-campanas-de-phishing-suplantando-a-la-agencia-tributaria-ahora-tambien-por-sms/)]
      - Están suplantando la web de Correos con kits vendidos en Telegram que usan sus bots para recopilar contraseñas. Y hay muchos kits así [[genbeta.com](https://www.genbeta.com/seguridad/estan-suplantando-web-correos-kits-vendidos-telegram-que-usan-sus-bots-para-recopilar-contrasenas-hay-muchos-kits-asi)]
      - Así pueden estafarte con la declaración de la Renta [[elcorreo.com](https://www.elcorreo.com/tecnologia/renta-2023-asi-ueden-estafarte-al-hacerse-pasar-por-la-agencia-tributaria-20230413150321-nt.html)]
      - Telegram abre paso a la venta de kits para suplantar webs como la de Correos a través de bots [[mundodeportivo.com](https://www.mundodeportivo.com/urbantecno/seguridad/telegram-abre-paso-a-la-venta-de-kits-para-suplantar-webs-como-la-de-correos-a-traves-de-bots)]
      - phishunt.io, cazando phishings [[derechodelared.com](https://derechodelared.com/phishunt-io-cazando-phishings/)]
      - Suplantan la identidad de tenistas como Rafa Nadal para incentivar la descarga de vídeos con malware [[20minutos.es](https://www.20minutos.es/tecnologia/ciberseguridad/suplantan-la-identidad-de-tenistas-como-rafa-nadal-para-incentivar-la-descarga-de-videos-con-malware-5031428/)]
      - El ciberataque vía Youtube que ha suplantado a Nadal o a Djokovic durante Wimbledon [[escudodigital.com](https://www.escudodigital.com/ciberseguridad/ciberataque-via-youtube-ha-suplantado-nadal-djokovic-durante-wimbledon_52375_102.html)]      
      - Continuan los SMS con falsos envíos de FedEx: cómo identificarlos y eliminar esta amenaza [[ESET blog](https://blogs.protegerse.com/2023/04/11/siguen-las-campanas-de-phishing-suplantando-a-la-agencia-tributaria-ahora-tambien-por-sms/)]
      - FedexBanker: El nuevo troyano bancario para Android que utiliza tus paquetes para robarte las credenciales [[hispasec.com](https://unaaldia.hispasec.com/2021/03/fedexbanker-el-nuevo-troyano-bancario-para-android.html)]
      - Los timos con criptomonedas que usan imágenes de famosos continúan muy activos [[ESET Blog](https://blogs.protegerse.com/2023/05/15/los-timos-de-las-criptomonedas-que-usan-imagenes-de-famosos-continuan-muy-activos/)]
      - How does a modded crypto wallet steal credentials of an user? [[@themalwarebug - medium.com](https://medium.com/@themalwarebug/how-does-a-modded-crypto-wallet-steal-credentials-of-an-user-29aaefc3f76e)]
      - Aplicación maliciosa para Android se hace pasar por una versión de la cartera de criptomonedas MetaMask [[ESET Blog](https://blogs.protegerse.com/2023/05/23/aplicacion-maliciosa-para-android-se-hace-pasar-por-una-version-de-la-cartera-de-criptomonedas-metamask/)]
      - Best Cyber Threat Intelligence Feeds [[silentpush.com](https://www.silentpush.com/blog/best-cyber-threat-intelligence-feeds)]

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      - Member of [CuratedIntel](https://twitter.com/CuratedIntel) Trust Group
      - Enjoy riding my bike or going to the gym (helps me a lot avoiding burnout)
      - I'm [Enneagram Type 5](https://www.enneagraminstitute.com/type-5)


# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
