# Site
repository: 0xDanielLopez/CV
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Daniel López
title: Security Engineer
email: brett.h@email.co.uk
website: daniel.tools

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: 0xDanielLopez
github_username:  0xDanielLopez
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 0xDanielLopez
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Daniel López, and I am a <mark>Security Engineer<mark> with over <mark>6 years of experience<mark> working in Security Operations Centers (SOC). Throughout these years, I have been involved in the analysis, containment and remediation of threats for international and strategic clients across multiple sectors.

  Also, in my spare time, I enjoy programming, building projects, and researching threats (which I often share on my Twitter account). I have a particular fondness for programming in Python/Bash and exploring technologies such as AWS or playing with APIs. These diverse interests enable me to stay up-to-date with the latest advancements in the field and continuously expand my skill set.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: phishunt.io
        link: phishunt.io
        # link_text: Project Website
        additional_links:
          - title:  phishunt.io
            icon: fab fa-fish
            url: phishunt.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Free feed of active phishing cases
        description: | # this will include new lines to allow paragraphs
          Project to find, analyze and monitor phishing sites.
      - layout: top-middle
        title: TweetFeed
        link: tweetfeed.live
        # link_text: Project Website
        additional_links:
          - title:  tweetfeed.live
            icon: fa-shield-halved
            url: tweetfeed.live
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          TweetFeed provides free feeds with Indicators Of Compromise (IOCs) shared at Twitter
        description: | # this will include new lines to allow paragraphs
          TweetFeed collects Indicators of Compromise (IOCs) shared by the infosec community at Twitter.


  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Citrix (Cloud Software Group)
        link: cloud.com
        # link_text: boringcompany.com
        sub_title: Security Engineer
        caption: Oct. 2020 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Working as a Security Engineer for Citrix -Cloud Software Group- multinational cloud computing and virtualization technology company.
      - layout: left
        title: Banco Santander
        link: bancosantander.es
        # link_text: boringcompany.com
        sub_title: Global SOC Security Analyst
        caption: Aug. 2018 - Oct. 2020
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Worked at Spain's largest bank SOC managing all types of cybersecurity alerts.
      - layout: left
        title: Deloitte
        link: deloitte.com
        # link_text: boringcompany.com
        sub_title: CyberSOC Security Analyst
        caption: Aug. 2017 - Aug. 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Worked at one of the largest professional services network on detecting and investigating all kind of cyberthreats.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Escuela Técnica Superior de Ingeniería (Universidad de Sevilla)
        caption: 2015 - 2019
        sub_title: Master's Degree in Telecommunications Engineering
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
- layout: left
        title: Escuela Técnica Superior de Ingeniería (Universidad de Sevilla)
        caption: 2011 - 2015
        sub_title: Degree in Telecommunications Engineering Technology
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
